language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"

# Cache dependencies in $HOME/.yarn-cache across builds
cache: yarn

# Run the the validate script
script: yarn run validate -- -- --ci --coverage --verbose

# Send coverage data to Coveralls
after_success:
  # Install coveralls globally
  - yarn global add coveralls

  # Retrieve the coverage information and send it to Coveralls
  - cat ./coverage/lcov.info | coveralls

# Build dist files
before_deploy: yarn run bundle:web

# Deploy to gh-pages branch on Github
deploy:
  skip_cleanup: true
  provider: script
  script:  ./_scripts/travis-deploy.sh
  on:
    branch: master
    node: "node"
