language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"

# Cache dependencies in $HOME/.yarn-cache across builds
cache: yarn

# Run the the validate script
script: yarn run validate:coverage

# Send coverage data to Coveralls
after_success: yarn run coveralls

# Build dist files
before_deploy: yarn run bundle:web

# Deploy to gh-pages branch on Github
deploy:
  skip_cleanup: true
  provider: script
  script:  ./_scripts/travis-deploy.sh
  on:
    branch: master
    node: "node"
