language: node_js
node_js:
  - "node"
  - "12"
  - "10"
  - "8"

cache: npm

# Generate all of the static data needed for salmon algorithms
before_script: npm run gen:all

# Run the the validate script
script: npm test -- --coverage

# Retrieve the coverage information and send it to Coveralls
after_success: cat ./coverage/lcov.info | npx coveralls
