import { SalmonRoute, Train } from '../utils/types'
import { AppState } from './reducers'

export const MOCK_ROUTES: SalmonRoute[] = [
  {
    backwardsRideTime: 5,
    backwardsRouteId: 'ROUTE 3',
    backwardsStation: 'RICH',
    backwardsTrain: {
      routeId: 'ROUTE 3',
      abbreviation: 'RICH',
      bikeflag: 1,
      color: 'ORANGE',
      destination: 'Richmond',
      direction: 'North',
      hexcolor: '#ff9933',
      length: 4,
      limited: 0,
      minutes: 2,
      platform: 1,
      delay: 0,
    },
    backwardsWaitTime: 7,
    returnRideTime: 4,
    returnRouteId: 'ROUTE 7',
    returnTrain: {
      routeId: 'ROUTE 7',
      abbreviation: 'MLBR',
      bikeflag: 1,
      color: 'RED',
      destination: 'Millbrae',
      direction: 'South',
      hexcolor: '#ff0000',
      length: 5,
      limited: 0,
      minutes: 14,
      platform: 2,
      delay: 0,
    },
    waitTime: 2,
  },
]
export const MOCK_ARRIVALS: Train[] = [
  {
    routeId: 'ROUTE 1',
    abbreviation: '24TH',
    bikeflag: 1,
    color: 'YELLOW',
    destination: '24th Street',
    direction: 'South',
    hexcolor: '#ffff33',
    length: 9,
    limited: 0,
    minutes: 9,
    platform: 2,
    delay: 0,
  },
  {
    routeId: 'ROUTE 1',
    abbreviation: 'SFIA',
    bikeflag: 1,
    color: 'YELLOW',
    destination: 'SF Airport',
    direction: 'South',
    hexcolor: '#ffff33',
    length: 10,
    limited: 0,
    minutes: 12,
    platform: 2,
    delay: 0,
  },
  {
    routeId: 'ROUTE 1',
    abbreviation: '24TH',
    bikeflag: 1,
    color: 'YELLOW',
    destination: '24th Street',
    direction: 'South',
    hexcolor: '#ffff33',
    length: 9,
    limited: 0,
    minutes: 20,
    platform: 2,
    delay: 0,
  },
  {
    routeId: 'ROUTE 1',
    abbreviation: 'SFIA',
    bikeflag: 1,
    color: 'YELLOW',
    destination: 'SF Airport',
    direction: 'South',
    hexcolor: '#ffff33',
    length: 10,
    limited: 0,
    minutes: 25,
    platform: 2,
    delay: 0,
  },
  {
    routeId: 'ROUTE 1',
    abbreviation: 'SFIA',
    bikeflag: 1,
    color: 'YELLOW',
    destination: 'SF Airport',
    direction: 'South',
    hexcolor: '#ffff33',
    length: 10,
    limited: 0,
    minutes: 40,
    platform: 2,
    delay: 0,
  },
]
export const MOCK_INITIAL_STATE: AppState = {
  origin: 'BALB',
  destination: '12TH',
  isFetching: false,
  salmonRoutes: [],
  arrivals: [],
  lastUpdated: null,
  numSalmonRoutes: 5,
  riskinessFactor: 0,
  numArrivals: 3,
}
